### ISSUE TITLE
Allow choice of SVG rendering engine

### ISSUE THREAD

**Issue by mbr4477** [TeamMeow/vscode-math-to-image#3]
Great extension, just what I needed for Markdown. Would it possible to include other rendering engines? For example, SVG rendering from [codecogs](https://www.codecogs.com/latex/eqneditor.php) in addition to GitHub. Don't have a lot of time on my hands right now, but I could look into contributing this if it seems like a good addition. Changing the engine could be a dropdown in the extension settings.

**Comment by spencerwooo** [comment]
Thanks, adding support for other rendering engines is definitely a thing we could improve! I'm quite occupied myself recently. Let me look into this when I have some time.

**Comment by spencerwooo** [comment]
Feature implemented as of version v0.1.0, closing.
